# Generated by Django 5.2.7 on 2025-10-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taska', '0002_studentleave_teacherregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleave',
            name='department',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentleave',
            name='rollno',
            field=models.IntegerField(),
        ),
    ]
