# Generated by Django 5.2.7 on 2025-10-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taska', '0003_studentleave_department_alter_studentleave_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleave',
            name='student_class',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentleave',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentleave',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentleave',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentleave',
            name='rollno',
            field=models.CharField(max_length=20),
        ),
    ]
