# Generated by Django 5.2.7 on 2025-10-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taska', '0004_studentleave_student_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
