# Generated by Django 5.2.7 on 2025-10-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taska', '0005_studentleave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherregister',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
